name: GenSource

on: workflow_dispatch

jobs:
  GenSource:
    runs-on: windows-2025
    strategy:
      fail-fast: false
      matrix:
        minecraft: [ 1.16.5, 1.17.1, 1.18.2, 1.19.2, 1.19.3, 1.19.4, 1.20.1 ]
    steps:
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'graalvm'
          java-version: '17.0.12'
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Gen Source
        run: ./gradlew genSource -PbuildVersion="${{ matrix.minecraft }}"
      - name: Upload Source
        uses: actions/upload-artifact@v4
        with:
          name: source-${{ matrix.minecraft }}
          path: C:\Users\runneradmin\.gradle\caches\fabric-loom\minecraftMaven\net\minecraft\minecraft-merged\*\*.jar